Add plugin skeleton
solutionDrive/sdEmotionsDeploymentShopware pull request #1
Opened 2018-08-10 10:09 UTC by jakoberr

2018-08-10 11:35 UTC, michz submitted a review, later dismissed

2018-08-10 14:05 UTC, sd-lueckel requested changes

2018-08-10 14:05 UTC, sd-lueckel commented on composer.json
> +    "description": "TODO Change this default description",
Change this default description

2018-08-15 15:23 UTC, michz approved these changes

2018-08-16 09:31 UTC, sd-lueckel approved these changes

2018-08-16 09:31 UTC, merged